# Generated by Django 6.0 on 2025-12-16 03:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=50)),
                ('channel_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('sender_id', models.CharField(max_length=50)),
                ('message_ts', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockKitTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='템플릿 이름')),
                ('template_type', models.CharField(choices=[('announcement', '공지 메시지'), ('home', '홈 화면'), ('modal', '모달'), ('reminder', '리마인더')], max_length=20, verbose_name='템플릿 유형')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('blocks', models.JSONField(verbose_name='Block Kit JSON')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': 'Block Kit 템플릿',
                'verbose_name_plural': 'Block Kit 템플릿 목록',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=100)),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='announcements.announcement')),
            ],
            options={
                'verbose_name': '읽음 확인',
                'verbose_name_plural': '읽음 확인 목록',
                'ordering': ['-confirmed_at'],
                'unique_together': {('announcement', 'user_id')},
            },
        ),
    ]
